# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "DataJoint"
tagline:          ''
description:      'Data management for science labs'
url:              https://datajoint.github.com
baseurl:          /

gems: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          0.2.0

github:
  repo:           https://github.com/datajoint
