# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            "|Data|Joint|"
tagline:          ''
description:      'Data organization for science labs'
url:              https://datajoint.github.com
baseurl:          /


paginate:         5

# Custom vars
version:          0.2.0

github:
  repo:           https://github.com/datajoint